language: java
jdk:

  openjdk8
branches:
only:
  - master

before_install:
2
  chmod +x gradlew
cache:
directories:
  - '$HOME/.m2/repository'
  - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
email:
recipients:
  - 3bgdragon@naver.com